#!/usr/bin/env python3
import argparse
import json
from datetime import date, timedelta
from pathlib import Path

TEMPLATE = """---
exception_id: {exception_id}
inv_scope: {inv_scope}
expiry: {expiry}
follow_up_ticket: {follow_up_ticket}
reason: {reason}
author: system
created_at: {created_at}
---

# Exception: {title}

This exception was auto-generated by local preflight because a structural change was detected,
but invariants linkage (manifest/docs with INV-###) was not included in the same commit.

## Reason

Auto-generated exception for structural-change linkage preflight.
Manual review is required to confirm final invariant linkage and closeout timeline.

## Evidence

{evidence}

## Mitigation

- Mechanical gates remain enabled (security + integrity + compliance checks).
- Exception is timeboxed and must be closed by the follow-up ticket before expiry.
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--detect", required=True, help="Path to detect.json")
    ap.add_argument("--inv-scope", default="change-rule", help="change-rule or comma-separated INV-### list")
    args = ap.parse_args()

    d = json.loads(Path(args.detect).read_text(encoding="utf-8"))

    today = date.today()
    created_at = today.isoformat()
    expiry = (today + timedelta(days=14)).isoformat()

    primary = d.get("primary_reason", "other")
    reason_types = d.get("reason_types", [])
    matched_files = d.get("matched_files", [])
    matches = d.get("matches", [])

    out_dir = Path("docs/invariants/exceptions")
    out_dir.mkdir(parents=True, exist_ok=True)

    filename = f"exception_change-rule_{primary}_{created_at}.md"
    out_path = out_dir / filename

    i = 1
    while out_path.exists():
        out_path = out_dir / f"exception_change-rule_{primary}_{created_at}_{i}.md"
        i += 1

    # Generate deterministic, non-placeholder identifiers.
    prefix = f"EXC-{created_at}-"
    seq = 1
    for p in out_dir.glob("*.md"):
        try:
            text = p.read_text(encoding="utf-8")
        except Exception:
            continue
        for line in text.splitlines():
            if not line.startswith("exception_id:"):
                continue
            candidate = line.split(":", 1)[1].strip()
            if candidate.startswith(prefix):
                try:
                    n = int(candidate.rsplit("-", 1)[1])
                    seq = max(seq, n + 1)
                except Exception:
                    pass
    exception_id = f"{prefix}{seq:02d}"
    follow_up_ticket = f"FOLLOWUP-AUTO-CHANGE-RULE-{created_at.replace('-', '')}-{seq:02d}"

    lines = [
        f"structural_change: {d.get('structural_change')}",
        f"confidence_hint: {d.get('confidence_hint')}",
        f"primary_reason: {primary}",
        f"reason_types: {', '.join(reason_types) if reason_types else 'none'}",
        "",
        "Matched files:",
    ]
    for f in matched_files[:50]:
        lines.append(f"- {f}")
    lines.append("")
    lines.append("Top matches:")
    for m in matches[:25]:
        lines.append(f"- {m.get('type')} | {m.get('file')} | {m.get('sign')}: {m.get('line')}")

    evidence = "\n".join(lines).strip()

    title = f"{primary} structural change without invariants linkage"
    reason = "Auto-generated: structural change detected; invariants linkage missing in commit."

    content = TEMPLATE.format(
        exception_id=exception_id,
        inv_scope=args.inv_scope,
        expiry=expiry,
        follow_up_ticket=follow_up_ticket,
        created_at=created_at,
        reason=reason,
        title=title,
        evidence=evidence,
    )
    out_path.write_text(content, encoding="utf-8")
    print(str(out_path))


if __name__ == "__main__":
    main()
