#!/bin/bash

# Verification script for TSK-P2-GOV-CONV-013
# Verify Phase-2 ratification artifact integrity

set -euo pipefail

TASK_ID="TSK-P2-GOV-CONV-013"
EVIDENCE_PATH="evidence/phase2/gov_conv_013_phase2_ratification_verifier.json"
GIT_SHA=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
TIMESTAMP_UTC=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Initialize checks array
checks=()

echo "Starting verification for ${TASK_ID}..."

# Check 1: Verify prerequisite task is complete
echo "Check 1: Verify prerequisite task complete"
if [ -f "tasks/TSK-P2-GOV-CONV-012/meta.yml" ]; then
    STATUS=$(grep "^status:" "tasks/TSK-P2-GOV-CONV-012/meta.yml" | cut -d: -f2- | tr -d ' ')
    if [ "$STATUS" = "completed" ]; then
        checks+=("prerequisite_task_complete:PASS")
        echo "✓ Prerequisite task TSK-P2-GOV-CONV-012 is completed"
    else
        checks+=("prerequisite_task_complete:FAIL")
        echo "✗ Prerequisite task TSK-P2-GOV-CONV-012 not completed: $STATUS"
        exit 1
    fi
else
    checks+=("prerequisite_task_complete:FAIL")
    echo "✗ Prerequisite task TSK-P2-GOV-CONV-012 not found"
    exit 1
fi

# Check 2: Verify reusable verifier exists
echo "Check 2: Verify reusable verifier exists"
if [ -f "scripts/audit/verify_phase2_ratification.sh" ]; then
    checks+=("reusable_verifier_exists:PASS")
    echo "✓ Reusable Phase-2 ratification verifier exists"
else
    checks+=("reusable_verifier_exists:FAIL")
    echo "✗ Reusable Phase-2 ratification verifier does not exist"
    exit 1
fi

# Check 3: Verify reusable verifier is executable
echo "Check 3: Verify reusable verifier is executable"
if [ -x "scripts/audit/verify_phase2_ratification.sh" ]; then
    checks+=("reusable_verifier_executable:PASS")
    echo "✓ Reusable verifier is executable"
else
    checks+=("reusable_verifier_executable:FAIL")
    echo "✗ Reusable verifier is not executable"
    exit 1
fi

# Check 4: Run reusable verifier
echo "Check 4: Run reusable verifier"
if bash scripts/audit/verify_phase2_ratification.sh; then
    checks+=("reusable_verifier_passes:PASS")
    echo "✓ Reusable verifier passes"
else
    checks+=("reusable_verifier_passes:FAIL")
    echo "✗ Reusable verifier fails"
    exit 1
fi

# Check 5: Verify evidence generated by reusable verifier
echo "Check 5: Verify evidence generated by reusable verifier"
if [ -f "evidence/phase2/phase2_ratification_status.json" ]; then
    checks+=("reusable_verifier_evidence:PASS")
    echo "✓ Reusable verifier evidence exists"
else
    checks+=("reusable_verifier_evidence:FAIL")
    echo "✗ Reusable verifier evidence does not exist"
    exit 1
fi

# Check 6: Verify evidence contains required fields
echo "Check 6: Verify evidence contains required fields"
if python3 -c "
import json
with open('evidence/phase2/phase2_ratification_status.json', 'r') as f:
    data = json.load(f)

required_fields = ['task_id', 'git_sha', 'timestamp_utc', 'status', 'ratification_status', 'validation_results']
missing_fields = [field for field in required_fields if field not in data]

if missing_fields:
    print(f'Missing required fields: {missing_fields}')
    exit(1)
else:
    print('Evidence has all required fields')
    exit(0)
" 2>/dev/null; then
    checks+=("evidence_required_fields:PASS")
    echo "✓ Evidence contains all required fields"
else
    checks+=("evidence_required_fields:FAIL")
    echo "✗ Evidence missing required fields"
    exit 1
fi

# Check 7: Verify evidence status is PASS
echo "Check 7: Verify evidence status is PASS"
EVIDENCE_STATUS=$(python3 -c "
import json
with open('evidence/phase2/phase2_ratification_status.json', 'r') as f:
    data = json.load(f)
print(data.get('status', ''))
" 2>/dev/null || echo "")

if [ "$EVIDENCE_STATUS" = "PASS" ]; then
    checks+=("evidence_status_pass:PASS")
    echo "✓ Evidence status is PASS"
else
    checks+=("evidence_status_pass:FAIL")
    echo "✗ Evidence status is not PASS: $EVIDENCE_STATUS"
    exit 1
fi

# Check 8: Verify ratification status is PASS
echo "Check 8: Verify ratification status is PASS"
RATIFICATION_STATUS=$(python3 -c "
import json
with open('evidence/phase2/phase2_ratification_status.json', 'r') as f:
    data = json.load(f)
print(data.get('ratification_status', ''))
" 2>/dev/null || echo "")

if [ "$RATIFICATION_STATUS" = "PASS" ]; then
    checks+=("ratification_status_pass:PASS")
    echo "✓ Ratification status is PASS"
else
    checks+=("ratification_status_pass:FAIL")
    echo "✗ Ratification status is not PASS: $RATIFICATION_STATUS"
    exit 1
fi

# Check 9: Verify no violations in evidence
echo "Check 9: Verify no violations in evidence"
VIOLATION_COUNT=$(python3 -c "
import json
with open('evidence/phase2/phase2_ratification_status.json', 'r') as f:
    data = json.load(f)
print(data.get('summary', {}).get('violation_count', 0))
" 2>/dev/null || echo "0")

if [ "$VIOLATION_COUNT" -eq 0 ]; then
    checks+=("no_violations:PASS")
    echo "✓ No violations in evidence"
else
    checks+=("no_violations:FAIL")
    echo "✗ Found $VIOLATION_COUNT violations in evidence"
    exit 1
fi

# Generate evidence JSON
cat > "$EVIDENCE_PATH" << EOF
{
  "task_id": "$TASK_ID",
  "git_sha": "$GIT_SHA",
  "timestamp_utc": "$TIMESTAMP_UTC",
  "status": "PASS",
  "checks": [
$(printf '    "%s"' "${checks[@]}" | paste -sd ',' -)
  ],
  "verifier_status": "PASS",
  "reusable_verifier": {
    "file": "scripts/audit/verify_phase2_ratification.sh",
    "exists": true,
    "executable": true,
    "passes": true,
    "evidence_file": "evidence/phase2/phase2_ratification_status.json"
  },
  "evidence_validation": {
    "evidence_exists": true,
    "required_fields_present": true,
    "status_pass": true,
    "ratification_status_pass": true,
    "violation_count": $VIOLATION_COUNT
  },
  "summary": {
    "total_checks": ${#checks[@]},
    "passed_checks": ${#checks[@]},
    "failed_checks": 0
  }
}
EOF

echo "Evidence written to $EVIDENCE_PATH"
echo "All checks passed"

exit 0
