#!/usr/bin/env python3
import json
import hashlib
import hmac
import base64
import sys
import os
from typing import List, Dict, Any

# ==============================================================================
# SYMPHONY IDENTITY TRUST BOUNDARY - CANONICAL SPECIFICATION (SEC-014)
# ==============================================================================
# This script is the NORMATIVE AUTHORITY for the Symphony Identity Protocol.
# All implementations (TSK-P1-SEC-011, 012, 013) MUST be proven against 
# the golden vectors generated by this script.
# ==============================================================================

CANONICAL_VERSION = "v1"
TUPLE_CONTRACT_VERSION = "v1.12"

class IdentityProtocolSpec:
    """Normative specification for Identity Reference derivation and attestation."""
    
    @staticmethod
    def canonical_json_bytes(obj: Dict[str, Any]) -> bytes:
        """
        Normative Canonical JSON rules (normalization grammar only):
        - UTF-8 encoding.
        - NFC normalization (assumed for this spec, but verifiers MUST enforce).
        - Lexicographic key ordering (raw UTF-8 octets).
        - No whitespace.
        - Integers only (mag bounded to 2^53 - 1).
        """
        # Ensure only integers for numbers
        for k, v in obj.items():
            if isinstance(v, float):
                raise ValueError(f"Floating point prohibited in identity spec: {k}={v}")
        
        # Sort keys by raw UTF-8 octet compare
        sorted_json = json.dumps(
            obj, 
            sort_keys=True, 
            separators=(',', ':'), 
            ensure_ascii=False
        ).encode('utf-8')
        return sorted_json

    @staticmethod
    def frame_field(field_bytes: bytes, use_u32: bool = False) -> bytes:
        """Binary length-prefixed framing."""
        length = len(field_bytes)
        if use_u32:
            if length > 0xFFFFFFFF:
                raise ValueError("Field exceeds u32 capacity")
            return length.to_bytes(4, byteorder='big') + field_bytes
        else:
            if length > 0xFFFF:
                raise ValueError("Field exceeds u16 capacity")
            return length.to_bytes(2, byteorder='big') + field_bytes

    @classmethod
    def generate_hmac_payload(cls, canon_v: str, domain: str, raw_pii_json: Dict[str, Any]) -> bytes:
        """
        Normative HMAC input framing:
        u16be(len(canon_v)) | canon_v | u16be(len(domain)) | domain | u32be(len(payload)) | payload
        """
        p_canon_v = canon_v.encode('utf-8')
        p_domain = domain.encode('utf-8')
        p_payload = cls.canonical_json_bytes(raw_pii_json)
        
        return (
            cls.frame_field(p_canon_v, use_u32=False) +
            cls.frame_field(p_domain, use_u32=False) +
            cls.frame_field(p_payload, use_u32=True)
        )

    @classmethod
    def generate_signature_payload(cls, fields: List[bytes]) -> bytes:
        """
        Normative Signature input framing (Fields 1-11):
        u16be(len(f1)) | f1 | ... | u16be(len(f11)) | f11
        """
        if len(fields) != 11:
            raise ValueError(f"Signature input MUST have exactly 11 fields, got {len(fields)}")
        
        payload = b""
        for f in fields:
            payload += cls.frame_field(f, use_u32=False)
        return payload

def generate_golden_vectors():
    """Generates the normative golden vectors for the 12-field protocol."""
    
    # Inputs
    raw_pii = {"email": "test@symphony.com", "name": "Test User"}
    domain = "symphony-kyc"
    dummy_key = b"SYMPHONY_HMAC_DUMMY_KEY_01234567" # 32 bytes
    
    # 1. HMAC Derivation
    hmac_input = IdentityProtocolSpec.generate_hmac_payload(CANONICAL_VERSION, domain, raw_pii)
    digest = hmac.new(dummy_key, hmac_input, hashlib.sha256).digest()
    identity_ref = base64.urlsafe_b64encode(digest).decode('utf-8').rstrip('=')
    
    # 2. Tuple Fields (Fields 1-11)
    fields = [
        identity_ref,            # 1. identity_ref
        "hmac-sha256-v1",        # 2. derivation_algorithm
        "pii-derivation-policy", # 3. identity_ref_policy_alias
        "key-012345",            # 4. identity_ref_key_id
        "1",                     # 5. identity_ref_key_version
        "pii-attestation-policy",# 6. attestation_policy_alias
        "signer-67890",          # 7. attestation_key_id
        "2",                     # 8. attestation_key_version
        CANONICAL_VERSION,       # 9. canonicalization_version
        domain,                  # 10. derivation_domain
        "1.12.0"                 # 11. schema_version
    ]
    
    # Convert fields to bytes for signing payload
    field_bytes = [f.encode('utf-8') for f in fields]
    signature_input = IdentityProtocolSpec.generate_signature_payload(field_bytes)
    
    # Generate vector report
    vector = {
        "metadata": {
            "authority": "TSK-P1-SEC-014",
            "contract": TUPLE_CONTRACT_VERSION,
            "normative_over_bytes": True
        },
        "inputs": {
            "raw_pii": raw_pii,
            "domain": domain,
            "hmac_key_hex": dummy_key.hex()
        },
        "outputs": {
            "hmac_input_hex": hmac_input.hex(),
            "identity_ref": identity_ref,
            "fields_1_11": fields,
            "signature_input_hex": signature_input.hex()
        }
    }
    
    return vector

if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--generate-fixtures":
        vector = generate_golden_vectors()
        fixture_path = "tasks/TSK-P1-SEC-014/fixtures/golden_vector_v1.json"
        os.makedirs(os.path.dirname(fixture_path), exist_ok=True)
        with open(fixture_path, "w") as f:
            json.dump(vector, f, indent=2)
        print(f"Fixture generated: {fixture_path}")
    else:
        # Self-test: check u16/u32 framing and canonical JSON
        try:
            IdentityProtocolSpec.canonical_json_bytes({"a": 1, "b": 2.0})
            print("FAILED: Did not catch floating point error")
            sys.exit(1)
        except ValueError:
            print("PASS: Caught prohibited floating point")
            
        test_obj = {"b": 2, "a": 1}
        c_bytes = IdentityProtocolSpec.canonical_json_bytes(test_obj)
        if c_bytes != b'{"a":1,"b":2}':
            print(f"FAILED: Canonical JSON ordering or separators: {c_bytes}")
            sys.exit(1)
        print("PASS: Canonical JSON logic verified")
        
        # Verify 11-field signature input constraint
        try:
            IdentityProtocolSpec.generate_signature_payload([b"a"] * 10)
            print("FAILED: Did not catch 11-field constraint violation")
            sys.exit(1)
        except ValueError:
            print("PASS: Caught incorrect field count for signature input")
            
        print("ALL SPEC GATES PASSED")
