-- 0095_pre_snapshot.sql - Pre-migration policy snapshot
-- Generated by Phase 0 script for audit and rollback purposes
-- Reference: docs/plans/phase1/TSK-RLS-ARCH-001/PLAN.md

-- This file contains the snapshot of all RLS policies on target tables
-- before the RLS architecture migration was applied.
-- Content will be populated by the Phase 0 enumeration script.

-- Placeholder for policy snapshot data
-- Actual policies will be captured by scripts/db/phase0_rls_enumerate.py
-- and written to this file during Phase 0 execution.
