#!/usr/bin/env bash
set -euo pipefail

PHASE0_EVIDENCE_ROOT="${PHASE0_EVIDENCE_ROOT:-evidence/phase0}"
PHASE0_CI_ONLY="${PHASE0_CI_ONLY:-1}"
PHASE0_REMEDIATION_TRACE_DIFF_MODE="${PHASE0_REMEDIATION_TRACE_DIFF_MODE:-range}"
PHASE0_REMEDIATION_TRACE_BASE_REF="${PHASE0_REMEDIATION_TRACE_BASE_REF:-refs/remotes/origin/main}"

export EVIDENCE_ROOT="$PHASE0_EVIDENCE_ROOT"
export CI_ONLY="$PHASE0_CI_ONLY"
export REMEDIATION_TRACE_DIFF_MODE="$PHASE0_REMEDIATION_TRACE_DIFF_MODE"
export REMEDIATION_TRACE_BASE_REF="$PHASE0_REMEDIATION_TRACE_BASE_REF"

if [[ -n "${GITHUB_ENV:-}" ]]; then
  {
    printf 'EVIDENCE_ROOT=%s\n' "$EVIDENCE_ROOT"
    printf 'CI_ONLY=%s\n' "$CI_ONLY"
    printf 'REMEDIATION_TRACE_DIFF_MODE=%s\n' "$REMEDIATION_TRACE_DIFF_MODE"
    printf 'REMEDIATION_TRACE_BASE_REF=%s\n' "$REMEDIATION_TRACE_BASE_REF"
  } >> "$GITHUB_ENV"
fi
