-- RLS Pre-Migration Snapshot (auto-generated by phase0_rls_enumerate.py)
-- Purpose: audit + rollback ONLY. NOT a correctness validator.
-- Generated: 2026-03-24T20:11:56Z
-- Policies captured: 23

BEGIN;

CREATE POLICY rls_tenant_isolation_billing_usage_events ON public.billing_usage_events
    AS RESTRICTIVE FOR ALL TO PUBLIC
    USING ((tenant_id = current_tenant_id_or_null()))
    WITH CHECK ((tenant_id = current_tenant_id_or_null()));

CREATE POLICY rls_tenant_isolation_escrow_accounts ON public.escrow_accounts
    AS RESTRICTIVE FOR ALL TO PUBLIC
    USING ((tenant_id = current_tenant_id_or_null()))
    WITH CHECK ((tenant_id = current_tenant_id_or_null()));

CREATE POLICY rls_tenant_isolation_escrow_envelopes ON public.escrow_envelopes
    AS RESTRICTIVE FOR ALL TO PUBLIC
    USING ((tenant_id = current_tenant_id_or_null()))
    WITH CHECK ((tenant_id = current_tenant_id_or_null()));

CREATE POLICY rls_tenant_isolation_escrow_events ON public.escrow_events
    AS RESTRICTIVE FOR ALL TO PUBLIC
    USING ((tenant_id = current_tenant_id_or_null()))
    WITH CHECK ((tenant_id = current_tenant_id_or_null()));

CREATE POLICY rls_tenant_isolation_escrow_reservations ON public.escrow_reservations
    AS RESTRICTIVE FOR ALL TO PUBLIC
    USING ((tenant_id = current_tenant_id_or_null()))
    WITH CHECK ((tenant_id = current_tenant_id_or_null()));

CREATE POLICY rls_tenant_isolation_external_proofs ON public.external_proofs
    AS RESTRICTIVE FOR ALL TO PUBLIC
    USING ((tenant_id = current_tenant_id_or_null()))
    WITH CHECK ((tenant_id = current_tenant_id_or_null()));

CREATE POLICY rls_tenant_isolation_member_device_events ON public.member_device_events
    AS RESTRICTIVE FOR ALL TO PUBLIC
    USING ((tenant_id = current_tenant_id_or_null()))
    WITH CHECK ((tenant_id = current_tenant_id_or_null()));

CREATE POLICY rls_tenant_isolation_member_devices ON public.member_devices
    AS RESTRICTIVE FOR ALL TO PUBLIC
    USING ((tenant_id = current_tenant_id_or_null()))
    WITH CHECK ((tenant_id = current_tenant_id_or_null()));

CREATE POLICY rls_tenant_isolation_members ON public.members
    AS RESTRICTIVE FOR ALL TO PUBLIC
    USING ((tenant_id = current_tenant_id_or_null()))
    WITH CHECK ((tenant_id = current_tenant_id_or_null()));

CREATE POLICY rls_tenant_isolation_payment_outbox_attempts ON public.payment_outbox_attempts
    AS RESTRICTIVE FOR ALL TO PUBLIC
    USING ((tenant_id = current_tenant_id_or_null()))
    WITH CHECK ((tenant_id = current_tenant_id_or_null()));

CREATE POLICY rls_tenant_isolation_payment_outbox_pending ON public.payment_outbox_pending
    AS RESTRICTIVE FOR ALL TO PUBLIC
    USING ((tenant_id = current_tenant_id_or_null()))
    WITH CHECK ((tenant_id = current_tenant_id_or_null()));

CREATE POLICY rls_tenant_isolation_persons ON public.persons
    AS RESTRICTIVE FOR ALL TO PUBLIC
    USING ((tenant_id = current_tenant_id_or_null()))
    WITH CHECK ((tenant_id = current_tenant_id_or_null()));

CREATE POLICY rls_tenant_isolation_program_migration_events ON public.program_migration_events
    AS RESTRICTIVE FOR ALL TO PUBLIC
    USING ((tenant_id = current_tenant_id_or_null()))
    WITH CHECK ((tenant_id = current_tenant_id_or_null()));

CREATE POLICY rls_tenant_isolation_program_supplier_allowlist ON public.program_supplier_allowlist
    AS RESTRICTIVE FOR ALL TO PUBLIC
    USING ((tenant_id = current_tenant_id_or_null()))
    WITH CHECK ((tenant_id = current_tenant_id_or_null()));

CREATE POLICY rls_tenant_isolation_programme_policy_binding ON public.programme_policy_binding
    AS PERMISSIVE FOR ALL TO PUBLIC
    USING (((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid) OR (current_setting('app.bypass_rls'::text, true) = 'on'::text)));

CREATE POLICY rls_tenant_isolation_programme_registry ON public.programme_registry
    AS PERMISSIVE FOR ALL TO PUBLIC
    USING (((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid) OR (current_setting('app.bypass_rls'::text, true) = 'on'::text)));

CREATE POLICY rls_tenant_isolation_programs ON public.programs
    AS RESTRICTIVE FOR ALL TO PUBLIC
    USING ((tenant_id = current_tenant_id_or_null()))
    WITH CHECK ((tenant_id = current_tenant_id_or_null()));

CREATE POLICY rls_tenant_isolation_sim_swap_alerts ON public.sim_swap_alerts
    AS RESTRICTIVE FOR ALL TO PUBLIC
    USING ((tenant_id = current_tenant_id_or_null()))
    WITH CHECK ((tenant_id = current_tenant_id_or_null()));

CREATE POLICY rls_tenant_isolation_supplier_registry ON public.supplier_registry
    AS RESTRICTIVE FOR ALL TO PUBLIC
    USING ((tenant_id = current_tenant_id_or_null()))
    WITH CHECK ((tenant_id = current_tenant_id_or_null()));

CREATE POLICY rls_tenant_isolation_tenant_clients ON public.tenant_clients
    AS RESTRICTIVE FOR ALL TO PUBLIC
    USING ((tenant_id = current_tenant_id_or_null()))
    WITH CHECK ((tenant_id = current_tenant_id_or_null()));

CREATE POLICY rls_tenant_isolation_tenant_members ON public.tenant_members
    AS RESTRICTIVE FOR ALL TO PUBLIC
    USING ((tenant_id = current_tenant_id_or_null()))
    WITH CHECK ((tenant_id = current_tenant_id_or_null()));

CREATE POLICY rls_tenant_isolation_tenant_registry ON public.tenant_registry
    AS PERMISSIVE FOR ALL TO PUBLIC
    USING (((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid) OR (current_setting('app.bypass_rls'::text, true) = 'on'::text)));

CREATE POLICY rls_tenant_isolation_tenants ON public.tenants
    AS RESTRICTIVE FOR ALL TO PUBLIC
    USING ((tenant_id = current_tenant_id_or_null()))
    WITH CHECK ((tenant_id = current_tenant_id_or_null()));

COMMIT;
